#!/usr/bin/env python3
"""Generate strategies/v8_15m_strategy.pine from indicators/v8_15m.pine.

The indicator is the single source of truth for the trading rules. This script
only swaps the declaration and adds broker orders at the points where the
indicator opens, cancels or re-stops a trade. Run it after every rule change:

    python3 tools/make_strategy.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "indicators" / "v8_15m.pine"
DST = ROOT / "strategies" / "v8_15m_strategy.pine"


def replace_once(text: str, old: str, new: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"anchor found {count} times, expected 1:\n{old}")
    return text.replace(old, new)


def main() -> None:
    s = SRC.read_text()

    s = replace_once(
        s,
        'indicator("v8 15M Entries", shorttitle = "v8 15M", overlay = true, max_lines_count = 500, max_labels_count = 500, max_boxes_count = 300, max_bars_back = 2000)',
        'strategy("v8 15M Strategy", shorttitle = "v8 15M Strat", overlay = true, max_lines_count = 500, max_labels_count = 500, max_boxes_count = 300, max_bars_back = 2000,\n'
        '     initial_capital = 120000, currency = currency.CAD, default_qty_type = strategy.fixed, pyramiding = 3,\n'
        '     process_orders_on_close = true, slippage = 5, commission_type = strategy.commission.percent, commission_value = 0,\n'
        '     margin_long = 1, margin_short = 1)',
    )

    # Open: market order at the signal close, or a limit at the retest level
    anchor = "                            trades.push(Trade.new(id, dir, bar_index, entry, sl, tg, riskPx, not chase, chase, lE, lS, lT))"
    s = replace_once(
        s,
        anchor,
        anchor + "\n"
        "                            strategy.entry(id, dir == 1 ? strategy.long : strategy.short, qty = units, limit = chase ? entry : na, comment = side + \" \" + z.setup + \" \" + z.trigName)\n"
        "                            strategy.exit(\"x\" + id, from_entry = id, stop = sl, limit = tg, comment_loss = \"SL\", comment_profit = \"TP\")",
    )

    # Limit expired unfilled: cancel the broker order too
    anchor = '                label.new(bar_index, t.entry, "limit expired", style = label.style_label_left, color = color.new(color.gray, 70), textcolor = color.white, size = size.tiny)'
    s = replace_once(s, anchor, anchor + "\n                strategy.cancel(t.id)")

    # Trailing stop moved (T3): move the broker stop
    anchor = "                        t.stop := cand"
    s = replace_once(
        s,
        anchor,
        anchor + "\n"
        "                        strategy.exit(\"x\" + t.id, from_entry = t.id, stop = t.stop, limit = t.tp, comment_loss = \"Trail\", comment_profit = \"TP\")",
    )

    header = (
        "// GENERATED by tools/make_strategy.py from indicators/v8_15m.pine. Do not edit by hand:\n"
        "// change the indicator, then run `python3 tools/make_strategy.py`.\n"
    )
    s = s.replace("//@version=6\n", "//@version=6\n" + header, 1)
    DST.parent.mkdir(exist_ok=True)
    DST.write_text(s)
    print(f"wrote {DST.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
